//engine_autogenerated_babel_config_version_0
// This file was generated by wix-one-app-engine on Fri May 07 2021

module.exports = {
  ...require('./node_modules/wix-one-app-engine/tools/engine_cli/etc/babel.config')
};
