// This file is auto-generated by wix-one-app-engine

export default {
  'one-app-module-habits': () => require('one-app-module-habits').default,
  '@wix/wix-one-app-platform': () => require('@wix/wix-one-app-platform').default,
  'demo-tab-module': () => require('demo-tab-module').default,
  'wix-one-app-member-view': () => require('wix-one-app-member-view').default
}
;