// This file is auto-generated by wix-one-app-engine

export default {
  'one-app-module-habits': () => require('/Users/vladislavt/Documents/projects/pathway/module.places.json'),
  '@wix/wix-one-app-platform': () => require('/Users/vladislavt/Documents/projects/pathway/node_modules/@wix/wix-one-app-platform/module.places.json'),
  'demo-tab-module': () => require('/Users/vladislavt/Documents/projects/pathway/demo/module.places.json'),
  'wix-one-app-member-view': () => require('/Users/vladislavt/Documents/projects/pathway/node_modules/wix-one-app-member-view/module.places.json')
};